### ISSUE TITLE
스크래핑된 데이터를 DB에 저장

### ISSUE THREAD

**Issue by Jaeho-99** [de-devcourse-2-3-2/crawling-visualization#13]
스크래핑 완료된 데이터들을 DB에 저장하는 방식 구현

**Comment by secureWKkim** [comment]
csv 파일을 최종 결과물, 배포판에서 사용할 것도 아니면서 csv 에 저장된 데이터 형태와 스키마 상 데이터 타입 간 관계 불일치 문제(ORM 문제와 유사)를 코드 레벨로 해소해 테스트 할 이유가 없기에 일정량 이상의 데이터가 모일 때마다 db write, commit 하는 방식으로 교체.

**Comment by secureWKkim** [comment]
클라이언트에서 사용자로부터 생성할 차트 종류가 선택된 뒤 백엔드 측에 전달된 시점에 크롤링&데베저장을 하도록 만들 것인가? 아니면 백엔드 단과 완전 별개로, 크롤링 작업 자체를 crawling 이하 폴더 안에서만 동작하고 멈출 수 있도록 만들 것인가?

전자가 되면 크롤링 프로세스, 클라&백엔&데베 프로세스가 서로 분리돼야 한다. 둘 간에 비동기로 동작해야 하는데 경험상 이게 구현이 훨씬 어려웠음

후자가 되면 둘은 원래부터 독립된 프로세스이므로 비동기 처리 등을 신경 쓰지 않아도 괜찮음
