### ISSUE TITLE
Read) 시즌별 스타일 추이

### ISSUE THREAD

**Issue by jiroh1** [de-devcourse-2-3-2/crawling-visualization#20]
1. 시즌 별 등록된 카테고리 각각의 개수 확인

**Comment by jiroh1** [comment]
로직변경)
1. 계절 별 ( season ) 설정 
2. 조회수 10,000 개 
3. 그 상태에서 카테고리 별  개수 확인
4. 상위 5개의 스타일 카테고리 확인 (w/ count) , 나머지는 모두 합해서 return

**Comment by cbs02112** [comment]
![image](https://github.com/de-devcourse-2-3-2/crawling-visualization/assets/36155664/429fcb9e-2de3-412f-8942-3cf4b66c7453)
