### ISSUE TITLE
Model serializer 모듈화

### ISSUE THREAD

**Issue by cbs02112** [de-devcourse-2-3-2/crawling-visualization#34]
차트 그리는 별도의 모듈을 사용하기 위해 이미 구현된 모델 시리얼라이저를 view가 아니라 임의의 함수로 바꿔주시면 감사하겠습니다. 리턴은 template 빼고 json만 있으면 됩니다.

**Comment by jiroh1** [comment]
slack message에 댓글로 질문 드리겠습니다.

**Comment by jiroh1** [comment]
완료했습니다.
