### ISSUE TITLE
PostgreSQL 연결 및 테이블 생성

### ISSUE THREAD

**Issue by cbs02112** [de-devcourse-2-3-2/crawling-visualization#5]

**Comment by secureWKkim** [comment]
connection config, 테이블 생성 쿼리는 postgres-write.py 에서 확인 가능

**Comment by secureWKkim** [comment]
<참고한 자료>
https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-foreign-key/

<쿼리 작성 시 고려한 사항들>
코딩 끝나고 적자
